name: github_user_explorer
description: A demo Flutter app showing GitHub users with best practices for fresher training.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_bloc: ^9.1.1
  get_it: ^7.7.0
  go_router: ^14.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
   - icons/
